# SecuredResources.properties
/hw04/convert=ROLE_USER,ROLE_ADMIN
/hw05/exchange=ROLE_ADMIN
/admin/allMembers=ROLE_ADMIN
/admin/memberList=ROLE_ADMIN
/member/changePassword=ROLE_USER
/member/mypage=ROLE_USER
/member/mypageBS=ROLE_USER
/member/modify=ROLE_USER