# driverClassName=oracle.jdbc.OracleDriver
# url=jdbc:oracle:thin:@192.168.35.94:1521/xe
driverClassName=com.p6spy.engine.spy.P6SpyDriver
url=jdbc:p6spy:oracle:thin:@192.168.35.94:1521/xe
username=bds02
password=java
maximumPoolSize=5
minimumIdle=3
connectionTimeoutMs=20000